export const COUNTRIES = [
  { title: "Afeganistão", value: "AF" },
  { title: "Albânia", value: "AL" },
  { title: "Argélia", value: "DZ" },
  { title: "Andorra", value: "AD" },
  { title: "Angola", value: "AO" },
  { title: "Argentina", value: "AR" },
  { title: "Armênia", value: "AM" },
  { title: "Austrália", value: "AU" },
  { title: "Áustria", value: "AT" },
  { title: "Azerbaijão", value: "AZ" },
  { title: "Bahamas", value: "BS" },
  { title: "Bahrein", value: "BH" },
  { title: "Bangladesh", value: "BD" },
  { title: "Barbados", value: "BB" },
  { title: "Bielorrússia", value: "BY" },
  { title: "Bélgica", value: "BE" },
  { title: "Belize", value: "BZ" },
  { title: "Benim", value: "BJ" },
  { title: "Butão", value: "BT" },
  { title: "Bolívia", value: "BO" },
  { title: "Bósnia e Herzegovina", value: "BA" },
  { title: "Botsuana", value: "BW" },
  { title: "Brasil", value: "BR" },
  { title: "Brunei", value: "BN" },
  { title: "Bulgária", value: "BG" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Burundi", value: "BI" },
  { title: "Camboja", value: "KH" },
  { title: "Camarões", value: "CM" },
  { title: "Canadá", value: "CA" },
  { title: "Cabo Verde", value: "CV" },
  { title: "República Centro-Africana", value: "CF" },
  { title: "Chade", value: "TD" },
  { title: "Chile", value: "CL" },
  { title: "China", value: "CN" },
  { title: "Colômbia", value: "CO" },
  { title: "Comores", value: "KM" },
  { title: "Congo (Brazzaville)", value: "CG" },
  { title: "Congo (Kinshasa)", value: "CD" },
  { title: "Costa Rica", value: "CR" },
  { title: "Croácia", value: "HR" },
  { title: "Cuba", value: "CU" },
  { title: "Chipre", value: "CY" },
  { title: "República Tcheca", value: "CZ" },
  { title: "Dinamarca", value: "DK" },
  { title: "Djibuti", value: "DJ" },
  { title: "Dominica", value: "DM" },
  { title: "República Dominicana", value: "DO" },
  { title: "Equador", value: "EC" },
  { title: "Egito", value: "EG" },
  { title: "El Salvador", value: "SV" },
  { title: "Guiné Equatorial", value: "GQ" },
  { title: "Eritreia", value: "ER" },
  { title: "Estônia", value: "EE" },
  { title: "Essuatíni", value: "SZ" },
  { title: "Etiópia", value: "ET" },
  { title: "Fiji", value: "FJ" },
  { title: "Finlândia", value: "FI" },
  { title: "França", value: "FR" },
  { title: "Gabão", value: "GA" },
  { title: "Gâmbia", value: "GM" },
  { title: "Geórgia", value: "GE" },
  { title: "Alemanha", value: "DE" },
  { title: "Gana", value: "GH" },
  { title: "Grécia", value: "GR" },
  { title: "Granada", value: "GD" },
  { title: "Guatemala", value: "GT" },
  { title: "Guiné", value: "GN" },
  { title: "Guiné-Bissau", value: "GW" },
  { title: "Guiana", value: "GY" },
  { title: "Haiti", value: "HT" },
  { title: "Honduras", value: "HN" },
  { title: "Hungria", value: "HU" },
  { title: "Islândia", value: "IS" },
  { title: "Índia", value: "IN" },
  { title: "Indonésia", value: "ID" },
  { title: "Irã", value: "IR" },
  { title: "Iraque", value: "IQ" },
  { title: "Irlanda", value: "IE" },
  { title: "Israel", value: "IL" },
  { title: "Itália", value: "IT" },
  { title: "Jamaica", value: "JM" },
  { title: "Japão", value: "JP" },
  { title: "Jordânia", value: "JO" },
  { title: "Cazaquistão", value: "KZ" },
  { title: "Quênia", value: "KE" },
  { title: "Quiribati", value: "KI" },
  { title: "Coreia do Norte", value: "KP" },
  { title: "Coreia do Sul", value: "KR" },
  { title: "Kuwait", value: "KW" },
  { title: "Quirguistão", value: "KG" },
  { title: "Laos", value: "LA" },
  { title: "Letônia", value: "LV" },
  { title: "Líbano", value: "LB" },
  { title: "Lesoto", value: "LS" },
  { title: "Libéria", value: "LR" },
  { title: "Líbia", value: "LY" },
  { title: "Liechtenstein", value: "LI" },
  { title: "Lituânia", value: "LT" },
  { title: "Luxemburgo", value: "LU" },
  { title: "Madagáscar", value: "MG" },
  { title: "Malawi", value: "MW" },
  { title: "Malásia", value: "MY" },
  { title: "Maldivas", value: "MV" },
  { title: "Mali", value: "ML" },
  { title: "Malta", value: "MT" },
  { title: "Ilhas Marshall", value: "MH" },
  { title: "Mauritânia", value: "MR" },
  { title: "Maurício", value: "MU" },
  { title: "México", value: "MX" },
  { title: "Micronésia", value: "FM" },
  { title: "Moldávia", value: "MD" },
  { title: "Mônaco", value: "MC" },
  { title: "Mongólia", value: "MN" },
  { title: "Montenegro", value: "ME" },
  { title: "Marrocos", value: "MA" },
  { title: "Moçambique", value: "MZ" },
  { title: "Myanmar", value: "MM" },
  { title: "Namíbia", value: "NA" },
  { title: "Nauru", value: "NR" },
  { title: "Nepal", value: "NP" },
  { title: "Países Baixos", value: "NL" },
  { title: "Nova Zelândia", value: "NZ" },
  { title: "Nicarágua", value: "NI" },
  { title: "Níger", value: "NE" },
  { title: "Nigéria", value: "NG" },
  { title: "Macedônia do Norte", value: "MK" },
  { title: "Noruega", value: "NO" },
  { title: "Omã", value: "OM" },
  { title: "Paquistão", value: "PK" },
  { title: "Palau", value: "PW" },
  { title: "Palestina", value: "PS" },
  { title: "Panamá", value: "PA" },
  { title: "Papua-Nova Guiné", value: "PG" },
  { title: "Paraguai", value: "PY" },
  { title: "Peru", value: "PE" },
  { title: "Filipinas", value: "PH" },
  { title: "Polônia", value: "PL" },
  { title: "Portugal", value: "PT" },
  { title: "Catar", value: "QA" },
  { title: "Romênia", value: "RO" },
  { title: "Rússia", value: "RU" },
  { title: "Ruanda", value: "RW" },
  { title: "São Cristóvão e Nevis", value: "KN" },
  { title: "Santa Lúcia", value: "LC" },
  { title: "São Vicente e Granadinas", value: "VC" },
  { title: "Samoa", value: "WS" },
  { title: "San Marino", value: "SM" },
  { title: "São Tomé e Príncipe", value: "ST" },
  { title: "Arábia Saudita", value: "SA" },
  { title: "Senegal", value: "SN" },
  { title: "Sérvia", value: "RS" },
  { title: "Seicheles", value: "SC" },
  { title: "Serra Leoa", value: "SL" },
  { title: "Singapura", value: "SG" },
  { title: "Eslováquia", value: "SK" },
  { title: "Eslovênia", value: "SI" },
  { title: "Ilhas Salomão", value: "SB" },
  { title: "Somália", value: "SO" },
  { title: "África do Sul", value: "ZA" },
  { title: "Sudão do Sul", value: "SS" },
  { title: "Espanha", value: "ES" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Sudão", value: "SD" },
  { title: "Suriname", value: "SR" },
  { title: "Suécia", value: "SE" },
  { title: "Suíça", value: "CH" },
  { title: "Síria", value: "SY" },
  { title: "Taiwan", value: "TW" },
  { title: "Tajiquistão", value: "TJ" },
  { title: "Tanzânia", value: "TZ" },
  { title: "Tailândia", value: "TH" },
  { title: "Timor-Leste", value: "TL" },
  { title: "Togo", value: "TG" },
  { title: "Tonga", value: "TO" },
  { title: "Trinidad e Tobago", value: "TT" },
  { title: "Tunísia", value: "TN" },
  { title: "Turquia", value: "TR" },
  { title: "Turcomenistão", value: "TM" },
  { title: "Tuvalu", value: "TV" },
  { title: "Uganda", value: "UG" },
  { title: "Ucrânia", value: "UA" },
  { title: "Emirados Árabes Unidos", value: "AE" },
  { title: "Reino Unido", value: "GB" },
  { title: "Estados Unidos", value: "US" },
  { title: "Uruguai", value: "UY" },
  { title: "Uzbequistão", value: "UZ" },
  { title: "Vanuatu", value: "VU" },
  { title: "Vaticano", value: "VA" },
  { title: "Venezuela", value: "VE" },
  { title: "Vietnã", value: "VN" },
  { title: "Iêmen", value: "YE" },
  { title: "Zâmbia", value: "ZM" },
  { title: "Zimbábue", value: "ZW" },
];

export const STATES = [
  { title: "Acre", value: "AC" },
  { title: "Alagoas", value: "AL" },
  { title: "Amapá", value: "AP" },
  { title: "Amazonas", value: "AM" },
  { title: "Bahia", value: "BA" },
  { title: "Ceará", value: "CE" },
  { title: "Distrito Federal", value: "DF" },
  { title: "Espírito Santo", value: "ES" },
  { title: "Goiás", value: "GO" },
  { title: "Maranhão", value: "MA" },
  { title: "Mato Grosso", value: "MT" },
  { title: "Mato Grosso do Sul", value: "MS" },
  { title: "Minas Gerais", value: "MG" },
  { title: "Pará", value: "PA" },
  { title: "Paraíba", value: "PB" },
  { title: "Paraná", value: "PR" },
  { title: "Pernambuco", value: "PE" },
  { title: "Piauí", value: "PI" },
  { title: "Rio de Janeiro", value: "RJ" },
  { title: "Rio Grande do Norte", value: "RN" },
  { title: "Rio Grande do Sul", value: "RS" },
  { title: "Rondônia", value: "RO" },
  { title: "Roraima", value: "RR" },
  { title: "Santa Catarina", value: "SC" },
  { title: "São Paulo", value: "SP" },
  { title: "Sergipe", value: "SE" },
  { title: "Tocantins", value: "TO" },
];

export const STATUS_OPTIONS = [
  { title: "Ativo", value: "ACTIVE" },
  { title: "Inativo", value: "INACTIVE" },
  { title: "Bloqueado", value: "BLOCKED" },
  { title: "Pendente", value: "PENDING" },
];

export const TYPES = [
  { title: "Pessoa Física", value: "F" },
  { title: "Pessoa Jurídica", value: "J" },
];

export const STATUS_MAP: Record<string, string> = {
  ACTIVE: "Ativo",
  INACTIVE: "Inativo",
  BLOCKED: "Bloqueado",
  PENDING: "Pendente",
};

export const STYLE_STATUS_MAP: Record<string, string> = {
  ACTIVE: "text-green-800 border-green-800 bg-green-500/60",
  INACTIVE: "text-blue-800 border-blue-800 bg-blue-500/60",
  BLOCKED: "text-red-800 border-red-800 bg-red-500/60",
  PENDING: "text-gray-800 border-gray-800 bg-gray-500/60",
};
