@baseUrl = http://localhost:8080/api/v1

### @name register

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "pedro",
    "email": "test2@email.com",
    "password": "123456",
    "confirmPassword": "123456"
}

### @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test2@email.com",
    "password": "123456"
}

### @name logout
GET {{baseUrl}}/auth/logout

### @name refresh
GET {{baseUrl}}/auth/refresh

### @name profile
GET {{baseUrl}}/user/profile

### @name update_avatar_profile
PATCH  {{baseUrl}}/user/update/avatar
Content-Type: multipart/form-data; boundary=---011000010111000001101001

-----011000010111000001101001
Content-Disposition: form-data; name="file"; filename="image-test-1.jpg"
Content-Type: image/jpeg

< ./tests/assets/image-test-1.jpg
-----011000010111000001101001

### @name update_profile
PATCH {{baseUrl}}/user/update/profile
Content-Type: application/json

{
  "name": "Pedro Luiz"
}

### @name list_stores
GET {{baseUrl}}/store/list

### @name get_store
GET {{baseUrl}}/store/get?code=IhylaSpcfI

### @name register_new_store
POST {{baseUrl}}/store/register
Content-Type: application/json

{
    "name": "Pedro Pizza Store",
    "address": "rua das 32"
}

### @name delete_store
DELETE {{baseUrl}}/store/delete?code=rSljGngwHd


### @name register_client
POST {{baseUrl}}/client/register
Content-Type: application/json

{
  "address": "123 Main Street",
  "state": "SP",
  "cityCode": "3550308",
  "name": "Empresa Exemplo",
  "tradeName": "Exemplo Ltda",
  "neighborhood": "Centro",
  "zipCode": "01000000",
  "city": "São Paulo",
  "areaCode": "11",
  "phone": "999999999",
  "type": "Matriz",
  "email": "contato3@exemplo.com",
  "country": "Brasil",
  "taxId": "12465678000199",
  "openingDate": "2020-01-01T00:00:00.000Z",
  "homepage": "https://www.exemplo.com",
  "status": "ACTIVE",
  "storeId": 1
}

### @name list_clients
GET {{baseUrl}}/client/list-clients
Content-Type: application/json

### @name get_client
GET {{baseUrl}}/client/profile/c7dSXXltY7

### @name update_client
PATCH {{baseUrl}}/client/update
Content-Type: application/json

{
  "code": "c7dSXXltY7",
  "address": "123 Main Street",
  "state": "SP",
  "cityCode": "3550308",
  "name": "Empresa Exemplo",
  "tradeName": "Exemplo Ltda",
  "neighborhood": "Centro",
  "zipCode": "01000000",
  "city": "Rio de Janeiro",
  "areaCode": "11",
  "phone": "999999999",
  "type": "Matriz",
  "email": "contato1@exemplo.com",
  "country": "Brasil",
  "taxId": "12465678000199",
  "openingDate": "2020-01-01T00:00:00.000Z",
  "homepage": "https://www.exemplo.com",
  "status": "ACTIVE",
  "storeId": 1
}

### @name export_all_clients

GET {{baseUrl}}/client/export-all-clients